# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(630, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 341, 271))
        self.calendarWidget.setObjectName("calendarWidget")
        self.Start_bnt = QtWidgets.QPushButton(self.centralwidget)
        self.Start_bnt.setGeometry(QtCore.QRect(350, 10, 131, 41))
        self.Start_bnt.setObjectName("Start_bnt")
        self.Stop_Bnt = QtWidgets.QPushButton(self.centralwidget)
        self.Stop_Bnt.setGeometry(QtCore.QRect(500, 10, 111, 41))
        self.Stop_Bnt.setObjectName("Stop_Bnt")
        self.avtostart = QtWidgets.QCheckBox(self.centralwidget)
        self.avtostart.setGeometry(QtCore.QRect(440, 60, 91, 31))
        self.avtostart.setObjectName("avtostart")
        self.video = QVideoWidget(self.centralwidget)
        self.video.setGeometry(QtCore.QRect(10, 280, 571, 251))
        self.video.setObjectName("video")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 630, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Start_bnt.setText(_translate("MainWindow", "Старт"))
        self.Stop_Bnt.setText(_translate("MainWindow", "СТОП"))
        self.avtostart.setText(_translate("MainWindow", "Автостарт"))
from PyQt5.QtMultimediaWidgets import QVideoWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
